// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMsg.proto

package org.example.Serialization.protobuf;

public final class ProtoMsg {
  private ProtoMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.Serialization.protobuf.Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *定义字段的一般形式为 type fileName = UniqueOrder
     * </pre>
     *
     * <code>uint32 version = 1;</code>
     */
    int getVersion();

    /**
     * <code>uint32 fversion = 2;</code>
     */
    int getFversion();

    /**
     * <pre>
     *必选的使用定义的类型，不然定义了没有用处
     * </pre>
     *
     * <code>.org.example.Serialization.protobuf.Msg.Magic magic = 3;</code>
     */
    boolean hasMagic();
    /**
     * <pre>
     *必选的使用定义的类型，不然定义了没有用处
     * </pre>
     *
     * <code>.org.example.Serialization.protobuf.Msg.Magic magic = 3;</code>
     */
    org.example.Serialization.protobuf.ProtoMsg.Msg.Magic getMagic();
    /**
     * <pre>
     *必选的使用定义的类型，不然定义了没有用处
     * </pre>
     *
     * <code>.org.example.Serialization.protobuf.Msg.Magic magic = 3;</code>
     */
    org.example.Serialization.protobuf.ProtoMsg.Msg.MagicOrBuilder getMagicOrBuilder();

    /**
     * <pre>
     *其他结构
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     *其他结构
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * <pre>
   *定义结构体，在java中会以内部类的形式存在上面的  java_outer_classname 外部内中，同时也是传输的主体
   * </pre>
   *
   * Protobuf type {@code org.example.Serialization.protobuf.Msg}
   */
  public  static final class Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.example.Serialization.protobuf.Msg)
      MsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Msg() {
      version_ = 0;
      fversion_ = 0;
      content_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readUInt32();
              break;
            }
            case 16: {

              fversion_ = input.readUInt32();
              break;
            }
            case 26: {
              org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.Builder subBuilder = null;
              if (magic_ != null) {
                subBuilder = magic_.toBuilder();
              }
              magic_ = input.readMessage(org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(magic_);
                magic_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.Serialization.protobuf.ProtoMsg.internal_static_org_example_Serialization_protobuf_Msg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.Serialization.protobuf.ProtoMsg.internal_static_org_example_Serialization_protobuf_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.Serialization.protobuf.ProtoMsg.Msg.class, org.example.Serialization.protobuf.ProtoMsg.Msg.Builder.class);
    }

    /**
     * <pre>
     *定义嵌套的内部复杂结构，比如message , 这里定义一个enum , 嵌套内部类 的 UniqueOrder 可以和外边重复
     * </pre>
     *
     * Protobuf enum {@code org.example.Serialization.protobuf.Msg.MagicEnum}
     */
    public enum MagicEnum
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PROUDCT = 0;</code>
       */
      PROUDCT(0),
      /**
       * <code>DEVPLOP = 1;</code>
       */
      DEVPLOP(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PROUDCT = 0;</code>
       */
      public static final int PROUDCT_VALUE = 0;
      /**
       * <code>DEVPLOP = 1;</code>
       */
      public static final int DEVPLOP_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MagicEnum valueOf(int value) {
        return forNumber(value);
      }

      public static MagicEnum forNumber(int value) {
        switch (value) {
          case 0: return PROUDCT;
          case 1: return DEVPLOP;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MagicEnum>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MagicEnum> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MagicEnum>() {
              public MagicEnum findValueByNumber(int number) {
                return MagicEnum.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.example.Serialization.protobuf.ProtoMsg.Msg.getDescriptor().getEnumTypes().get(0);
      }

      private static final MagicEnum[] VALUES = values();

      public static MagicEnum valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MagicEnum(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.example.Serialization.protobuf.Msg.MagicEnum)
    }

    public interface MagicOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.example.Serialization.protobuf.Msg.Magic)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       *魔数说明
       * </pre>
       *
       * <code>string desc = 1;</code>
       */
      java.lang.String getDesc();
      /**
       * <pre>
       *魔数说明
       * </pre>
       *
       * <code>string desc = 1;</code>
       */
      com.google.protobuf.ByteString
          getDescBytes();

      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>.org.example.Serialization.protobuf.Msg.MagicEnum magicEnum = 2;</code>
       */
      int getMagicEnumValue();
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>.org.example.Serialization.protobuf.Msg.MagicEnum magicEnum = 2;</code>
       */
      org.example.Serialization.protobuf.ProtoMsg.Msg.MagicEnum getMagicEnum();
    }
    /**
     * <pre>
     *定义一个其他的复杂的结构, 复用上面的枚举类型
     * </pre>
     *
     * Protobuf type {@code org.example.Serialization.protobuf.Msg.Magic}
     */
    public  static final class Magic extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:org.example.Serialization.protobuf.Msg.Magic)
        MagicOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Magic.newBuilder() to construct.
      private Magic(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Magic() {
        desc_ = "";
        magicEnum_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Magic(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                desc_ = s;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();

                magicEnum_ = rawValue;
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.Serialization.protobuf.ProtoMsg.internal_static_org_example_Serialization_protobuf_Msg_Magic_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.Serialization.protobuf.ProtoMsg.internal_static_org_example_Serialization_protobuf_Msg_Magic_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.class, org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.Builder.class);
      }

      public static final int DESC_FIELD_NUMBER = 1;
      private volatile java.lang.Object desc_;
      /**
       * <pre>
       *魔数说明
       * </pre>
       *
       * <code>string desc = 1;</code>
       */
      public java.lang.String getDesc() {
        java.lang.Object ref = desc_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          desc_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *魔数说明
       * </pre>
       *
       * <code>string desc = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDescBytes() {
        java.lang.Object ref = desc_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          desc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int MAGICENUM_FIELD_NUMBER = 2;
      private int magicEnum_;
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>.org.example.Serialization.protobuf.Msg.MagicEnum magicEnum = 2;</code>
       */
      public int getMagicEnumValue() {
        return magicEnum_;
      }
      /**
       * <pre>
       *类型
       * </pre>
       *
       * <code>.org.example.Serialization.protobuf.Msg.MagicEnum magicEnum = 2;</code>
       */
      public org.example.Serialization.protobuf.ProtoMsg.Msg.MagicEnum getMagicEnum() {
        @SuppressWarnings("deprecation")
        org.example.Serialization.protobuf.ProtoMsg.Msg.MagicEnum result = org.example.Serialization.protobuf.ProtoMsg.Msg.MagicEnum.valueOf(magicEnum_);
        return result == null ? org.example.Serialization.protobuf.ProtoMsg.Msg.MagicEnum.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getDescBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, desc_);
        }
        if (magicEnum_ != org.example.Serialization.protobuf.ProtoMsg.Msg.MagicEnum.PROUDCT.getNumber()) {
          output.writeEnum(2, magicEnum_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getDescBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, desc_);
        }
        if (magicEnum_ != org.example.Serialization.protobuf.ProtoMsg.Msg.MagicEnum.PROUDCT.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, magicEnum_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.example.Serialization.protobuf.ProtoMsg.Msg.Magic)) {
          return super.equals(obj);
        }
        org.example.Serialization.protobuf.ProtoMsg.Msg.Magic other = (org.example.Serialization.protobuf.ProtoMsg.Msg.Magic) obj;

        boolean result = true;
        result = result && getDesc()
            .equals(other.getDesc());
        result = result && magicEnum_ == other.magicEnum_;
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + DESC_FIELD_NUMBER;
        hash = (53 * hash) + getDesc().hashCode();
        hash = (37 * hash) + MAGICENUM_FIELD_NUMBER;
        hash = (53 * hash) + magicEnum_;
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.example.Serialization.protobuf.ProtoMsg.Msg.Magic parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.example.Serialization.protobuf.ProtoMsg.Msg.Magic parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.example.Serialization.protobuf.ProtoMsg.Msg.Magic parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.example.Serialization.protobuf.ProtoMsg.Msg.Magic parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.example.Serialization.protobuf.ProtoMsg.Msg.Magic parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.example.Serialization.protobuf.ProtoMsg.Msg.Magic parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.example.Serialization.protobuf.ProtoMsg.Msg.Magic parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.example.Serialization.protobuf.ProtoMsg.Msg.Magic parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.example.Serialization.protobuf.ProtoMsg.Msg.Magic parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.example.Serialization.protobuf.ProtoMsg.Msg.Magic parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.example.Serialization.protobuf.ProtoMsg.Msg.Magic parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.example.Serialization.protobuf.ProtoMsg.Msg.Magic parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.example.Serialization.protobuf.ProtoMsg.Msg.Magic prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       *定义一个其他的复杂的结构, 复用上面的枚举类型
       * </pre>
       *
       * Protobuf type {@code org.example.Serialization.protobuf.Msg.Magic}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:org.example.Serialization.protobuf.Msg.Magic)
          org.example.Serialization.protobuf.ProtoMsg.Msg.MagicOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.example.Serialization.protobuf.ProtoMsg.internal_static_org_example_Serialization_protobuf_Msg_Magic_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.example.Serialization.protobuf.ProtoMsg.internal_static_org_example_Serialization_protobuf_Msg_Magic_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.class, org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.Builder.class);
        }

        // Construct using org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          desc_ = "";

          magicEnum_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.example.Serialization.protobuf.ProtoMsg.internal_static_org_example_Serialization_protobuf_Msg_Magic_descriptor;
        }

        @java.lang.Override
        public org.example.Serialization.protobuf.ProtoMsg.Msg.Magic getDefaultInstanceForType() {
          return org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.getDefaultInstance();
        }

        @java.lang.Override
        public org.example.Serialization.protobuf.ProtoMsg.Msg.Magic build() {
          org.example.Serialization.protobuf.ProtoMsg.Msg.Magic result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.example.Serialization.protobuf.ProtoMsg.Msg.Magic buildPartial() {
          org.example.Serialization.protobuf.ProtoMsg.Msg.Magic result = new org.example.Serialization.protobuf.ProtoMsg.Msg.Magic(this);
          result.desc_ = desc_;
          result.magicEnum_ = magicEnum_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.example.Serialization.protobuf.ProtoMsg.Msg.Magic) {
            return mergeFrom((org.example.Serialization.protobuf.ProtoMsg.Msg.Magic)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.example.Serialization.protobuf.ProtoMsg.Msg.Magic other) {
          if (other == org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.getDefaultInstance()) return this;
          if (!other.getDesc().isEmpty()) {
            desc_ = other.desc_;
            onChanged();
          }
          if (other.magicEnum_ != 0) {
            setMagicEnumValue(other.getMagicEnumValue());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.example.Serialization.protobuf.ProtoMsg.Msg.Magic parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.example.Serialization.protobuf.ProtoMsg.Msg.Magic) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object desc_ = "";
        /**
         * <pre>
         *魔数说明
         * </pre>
         *
         * <code>string desc = 1;</code>
         */
        public java.lang.String getDesc() {
          java.lang.Object ref = desc_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            desc_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         *魔数说明
         * </pre>
         *
         * <code>string desc = 1;</code>
         */
        public com.google.protobuf.ByteString
            getDescBytes() {
          java.lang.Object ref = desc_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            desc_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *魔数说明
         * </pre>
         *
         * <code>string desc = 1;</code>
         */
        public Builder setDesc(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          desc_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *魔数说明
         * </pre>
         *
         * <code>string desc = 1;</code>
         */
        public Builder clearDesc() {
          
          desc_ = getDefaultInstance().getDesc();
          onChanged();
          return this;
        }
        /**
         * <pre>
         *魔数说明
         * </pre>
         *
         * <code>string desc = 1;</code>
         */
        public Builder setDescBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          desc_ = value;
          onChanged();
          return this;
        }

        private int magicEnum_ = 0;
        /**
         * <pre>
         *类型
         * </pre>
         *
         * <code>.org.example.Serialization.protobuf.Msg.MagicEnum magicEnum = 2;</code>
         */
        public int getMagicEnumValue() {
          return magicEnum_;
        }
        /**
         * <pre>
         *类型
         * </pre>
         *
         * <code>.org.example.Serialization.protobuf.Msg.MagicEnum magicEnum = 2;</code>
         */
        public Builder setMagicEnumValue(int value) {
          magicEnum_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *类型
         * </pre>
         *
         * <code>.org.example.Serialization.protobuf.Msg.MagicEnum magicEnum = 2;</code>
         */
        public org.example.Serialization.protobuf.ProtoMsg.Msg.MagicEnum getMagicEnum() {
          @SuppressWarnings("deprecation")
          org.example.Serialization.protobuf.ProtoMsg.Msg.MagicEnum result = org.example.Serialization.protobuf.ProtoMsg.Msg.MagicEnum.valueOf(magicEnum_);
          return result == null ? org.example.Serialization.protobuf.ProtoMsg.Msg.MagicEnum.UNRECOGNIZED : result;
        }
        /**
         * <pre>
         *类型
         * </pre>
         *
         * <code>.org.example.Serialization.protobuf.Msg.MagicEnum magicEnum = 2;</code>
         */
        public Builder setMagicEnum(org.example.Serialization.protobuf.ProtoMsg.Msg.MagicEnum value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          magicEnum_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <pre>
         *类型
         * </pre>
         *
         * <code>.org.example.Serialization.protobuf.Msg.MagicEnum magicEnum = 2;</code>
         */
        public Builder clearMagicEnum() {
          
          magicEnum_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:org.example.Serialization.protobuf.Msg.Magic)
      }

      // @@protoc_insertion_point(class_scope:org.example.Serialization.protobuf.Msg.Magic)
      private static final org.example.Serialization.protobuf.ProtoMsg.Msg.Magic DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.example.Serialization.protobuf.ProtoMsg.Msg.Magic();
      }

      public static org.example.Serialization.protobuf.ProtoMsg.Msg.Magic getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Magic>
          PARSER = new com.google.protobuf.AbstractParser<Magic>() {
        @java.lang.Override
        public Magic parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Magic(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Magic> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Magic> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.example.Serialization.protobuf.ProtoMsg.Msg.Magic getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <pre>
     *定义字段的一般形式为 type fileName = UniqueOrder
     * </pre>
     *
     * <code>uint32 version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int FVERSION_FIELD_NUMBER = 2;
    private int fversion_;
    /**
     * <code>uint32 fversion = 2;</code>
     */
    public int getFversion() {
      return fversion_;
    }

    public static final int MAGIC_FIELD_NUMBER = 3;
    private org.example.Serialization.protobuf.ProtoMsg.Msg.Magic magic_;
    /**
     * <pre>
     *必选的使用定义的类型，不然定义了没有用处
     * </pre>
     *
     * <code>.org.example.Serialization.protobuf.Msg.Magic magic = 3;</code>
     */
    public boolean hasMagic() {
      return magic_ != null;
    }
    /**
     * <pre>
     *必选的使用定义的类型，不然定义了没有用处
     * </pre>
     *
     * <code>.org.example.Serialization.protobuf.Msg.Magic magic = 3;</code>
     */
    public org.example.Serialization.protobuf.ProtoMsg.Msg.Magic getMagic() {
      return magic_ == null ? org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.getDefaultInstance() : magic_;
    }
    /**
     * <pre>
     *必选的使用定义的类型，不然定义了没有用处
     * </pre>
     *
     * <code>.org.example.Serialization.protobuf.Msg.Magic magic = 3;</code>
     */
    public org.example.Serialization.protobuf.ProtoMsg.Msg.MagicOrBuilder getMagicOrBuilder() {
      return getMagic();
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     *其他结构
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *其他结构
     * </pre>
     *
     * <code>string content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeUInt32(1, version_);
      }
      if (fversion_ != 0) {
        output.writeUInt32(2, fversion_);
      }
      if (magic_ != null) {
        output.writeMessage(3, getMagic());
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (fversion_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, fversion_);
      }
      if (magic_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getMagic());
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.Serialization.protobuf.ProtoMsg.Msg)) {
        return super.equals(obj);
      }
      org.example.Serialization.protobuf.ProtoMsg.Msg other = (org.example.Serialization.protobuf.ProtoMsg.Msg) obj;

      boolean result = true;
      result = result && (getVersion()
          == other.getVersion());
      result = result && (getFversion()
          == other.getFversion());
      result = result && (hasMagic() == other.hasMagic());
      if (hasMagic()) {
        result = result && getMagic()
            .equals(other.getMagic());
      }
      result = result && getContent()
          .equals(other.getContent());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + FVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getFversion();
      if (hasMagic()) {
        hash = (37 * hash) + MAGIC_FIELD_NUMBER;
        hash = (53 * hash) + getMagic().hashCode();
      }
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.Serialization.protobuf.ProtoMsg.Msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Serialization.protobuf.ProtoMsg.Msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Serialization.protobuf.ProtoMsg.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Serialization.protobuf.ProtoMsg.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Serialization.protobuf.ProtoMsg.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.Serialization.protobuf.ProtoMsg.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.Serialization.protobuf.ProtoMsg.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.Serialization.protobuf.ProtoMsg.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.Serialization.protobuf.ProtoMsg.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.Serialization.protobuf.ProtoMsg.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.Serialization.protobuf.ProtoMsg.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.Serialization.protobuf.ProtoMsg.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.Serialization.protobuf.ProtoMsg.Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *定义结构体，在java中会以内部类的形式存在上面的  java_outer_classname 外部内中，同时也是传输的主体
     * </pre>
     *
     * Protobuf type {@code org.example.Serialization.protobuf.Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.Serialization.protobuf.Msg)
        org.example.Serialization.protobuf.ProtoMsg.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.Serialization.protobuf.ProtoMsg.internal_static_org_example_Serialization_protobuf_Msg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.Serialization.protobuf.ProtoMsg.internal_static_org_example_Serialization_protobuf_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.Serialization.protobuf.ProtoMsg.Msg.class, org.example.Serialization.protobuf.ProtoMsg.Msg.Builder.class);
      }

      // Construct using org.example.Serialization.protobuf.ProtoMsg.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        fversion_ = 0;

        if (magicBuilder_ == null) {
          magic_ = null;
        } else {
          magic_ = null;
          magicBuilder_ = null;
        }
        content_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.Serialization.protobuf.ProtoMsg.internal_static_org_example_Serialization_protobuf_Msg_descriptor;
      }

      @java.lang.Override
      public org.example.Serialization.protobuf.ProtoMsg.Msg getDefaultInstanceForType() {
        return org.example.Serialization.protobuf.ProtoMsg.Msg.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.Serialization.protobuf.ProtoMsg.Msg build() {
        org.example.Serialization.protobuf.ProtoMsg.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.Serialization.protobuf.ProtoMsg.Msg buildPartial() {
        org.example.Serialization.protobuf.ProtoMsg.Msg result = new org.example.Serialization.protobuf.ProtoMsg.Msg(this);
        result.version_ = version_;
        result.fversion_ = fversion_;
        if (magicBuilder_ == null) {
          result.magic_ = magic_;
        } else {
          result.magic_ = magicBuilder_.build();
        }
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.Serialization.protobuf.ProtoMsg.Msg) {
          return mergeFrom((org.example.Serialization.protobuf.ProtoMsg.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.Serialization.protobuf.ProtoMsg.Msg other) {
        if (other == org.example.Serialization.protobuf.ProtoMsg.Msg.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getFversion() != 0) {
          setFversion(other.getFversion());
        }
        if (other.hasMagic()) {
          mergeMagic(other.getMagic());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.Serialization.protobuf.ProtoMsg.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.Serialization.protobuf.ProtoMsg.Msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int version_ ;
      /**
       * <pre>
       *定义字段的一般形式为 type fileName = UniqueOrder
       * </pre>
       *
       * <code>uint32 version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       *定义字段的一般形式为 type fileName = UniqueOrder
       * </pre>
       *
       * <code>uint32 version = 1;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *定义字段的一般形式为 type fileName = UniqueOrder
       * </pre>
       *
       * <code>uint32 version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private int fversion_ ;
      /**
       * <code>uint32 fversion = 2;</code>
       */
      public int getFversion() {
        return fversion_;
      }
      /**
       * <code>uint32 fversion = 2;</code>
       */
      public Builder setFversion(int value) {
        
        fversion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 fversion = 2;</code>
       */
      public Builder clearFversion() {
        
        fversion_ = 0;
        onChanged();
        return this;
      }

      private org.example.Serialization.protobuf.ProtoMsg.Msg.Magic magic_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.example.Serialization.protobuf.ProtoMsg.Msg.Magic, org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.Builder, org.example.Serialization.protobuf.ProtoMsg.Msg.MagicOrBuilder> magicBuilder_;
      /**
       * <pre>
       *必选的使用定义的类型，不然定义了没有用处
       * </pre>
       *
       * <code>.org.example.Serialization.protobuf.Msg.Magic magic = 3;</code>
       */
      public boolean hasMagic() {
        return magicBuilder_ != null || magic_ != null;
      }
      /**
       * <pre>
       *必选的使用定义的类型，不然定义了没有用处
       * </pre>
       *
       * <code>.org.example.Serialization.protobuf.Msg.Magic magic = 3;</code>
       */
      public org.example.Serialization.protobuf.ProtoMsg.Msg.Magic getMagic() {
        if (magicBuilder_ == null) {
          return magic_ == null ? org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.getDefaultInstance() : magic_;
        } else {
          return magicBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *必选的使用定义的类型，不然定义了没有用处
       * </pre>
       *
       * <code>.org.example.Serialization.protobuf.Msg.Magic magic = 3;</code>
       */
      public Builder setMagic(org.example.Serialization.protobuf.ProtoMsg.Msg.Magic value) {
        if (magicBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          magic_ = value;
          onChanged();
        } else {
          magicBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *必选的使用定义的类型，不然定义了没有用处
       * </pre>
       *
       * <code>.org.example.Serialization.protobuf.Msg.Magic magic = 3;</code>
       */
      public Builder setMagic(
          org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.Builder builderForValue) {
        if (magicBuilder_ == null) {
          magic_ = builderForValue.build();
          onChanged();
        } else {
          magicBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *必选的使用定义的类型，不然定义了没有用处
       * </pre>
       *
       * <code>.org.example.Serialization.protobuf.Msg.Magic magic = 3;</code>
       */
      public Builder mergeMagic(org.example.Serialization.protobuf.ProtoMsg.Msg.Magic value) {
        if (magicBuilder_ == null) {
          if (magic_ != null) {
            magic_ =
              org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.newBuilder(magic_).mergeFrom(value).buildPartial();
          } else {
            magic_ = value;
          }
          onChanged();
        } else {
          magicBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *必选的使用定义的类型，不然定义了没有用处
       * </pre>
       *
       * <code>.org.example.Serialization.protobuf.Msg.Magic magic = 3;</code>
       */
      public Builder clearMagic() {
        if (magicBuilder_ == null) {
          magic_ = null;
          onChanged();
        } else {
          magic_ = null;
          magicBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *必选的使用定义的类型，不然定义了没有用处
       * </pre>
       *
       * <code>.org.example.Serialization.protobuf.Msg.Magic magic = 3;</code>
       */
      public org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.Builder getMagicBuilder() {
        
        onChanged();
        return getMagicFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *必选的使用定义的类型，不然定义了没有用处
       * </pre>
       *
       * <code>.org.example.Serialization.protobuf.Msg.Magic magic = 3;</code>
       */
      public org.example.Serialization.protobuf.ProtoMsg.Msg.MagicOrBuilder getMagicOrBuilder() {
        if (magicBuilder_ != null) {
          return magicBuilder_.getMessageOrBuilder();
        } else {
          return magic_ == null ?
              org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.getDefaultInstance() : magic_;
        }
      }
      /**
       * <pre>
       *必选的使用定义的类型，不然定义了没有用处
       * </pre>
       *
       * <code>.org.example.Serialization.protobuf.Msg.Magic magic = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.example.Serialization.protobuf.ProtoMsg.Msg.Magic, org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.Builder, org.example.Serialization.protobuf.ProtoMsg.Msg.MagicOrBuilder> 
          getMagicFieldBuilder() {
        if (magicBuilder_ == null) {
          magicBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.example.Serialization.protobuf.ProtoMsg.Msg.Magic, org.example.Serialization.protobuf.ProtoMsg.Msg.Magic.Builder, org.example.Serialization.protobuf.ProtoMsg.Msg.MagicOrBuilder>(
                  getMagic(),
                  getParentForChildren(),
                  isClean());
          magic_ = null;
        }
        return magicBuilder_;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       *其他结构
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *其他结构
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *其他结构
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *其他结构
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *其他结构
       * </pre>
       *
       * <code>string content = 4;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.example.Serialization.protobuf.Msg)
    }

    // @@protoc_insertion_point(class_scope:org.example.Serialization.protobuf.Msg)
    private static final org.example.Serialization.protobuf.ProtoMsg.Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.Serialization.protobuf.ProtoMsg.Msg();
    }

    public static org.example.Serialization.protobuf.ProtoMsg.Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg>
        PARSER = new com.google.protobuf.AbstractParser<Msg>() {
      @java.lang.Override
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.Serialization.protobuf.ProtoMsg.Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_Serialization_protobuf_Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_Serialization_protobuf_Msg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_Serialization_protobuf_Msg_Magic_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_Serialization_protobuf_Msg_Magic_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ProtoMsg.proto\022\"org.example.Serializat" +
      "ion.protobuf\"\373\001\n\003Msg\022\017\n\007version\030\001 \001(\r\022\020\n" +
      "\010fversion\030\002 \001(\r\022<\n\005magic\030\003 \001(\0132-.org.exa" +
      "mple.Serialization.protobuf.Msg.Magic\022\017\n" +
      "\007content\030\004 \001(\t\032[\n\005Magic\022\014\n\004desc\030\001 \001(\t\022D\n" +
      "\tmagicEnum\030\002 \001(\01621.org.example.Serializa" +
      "tion.protobuf.Msg.MagicEnum\"%\n\tMagicEnum" +
      "\022\013\n\007PROUDCT\020\000\022\013\n\007DEVPLOP\020\001B.\n\"org.exampl" +
      "e.Serialization.protobufB\010ProtoMsgb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_example_Serialization_protobuf_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_Serialization_protobuf_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_Serialization_protobuf_Msg_descriptor,
        new java.lang.String[] { "Version", "Fversion", "Magic", "Content", });
    internal_static_org_example_Serialization_protobuf_Msg_Magic_descriptor =
      internal_static_org_example_Serialization_protobuf_Msg_descriptor.getNestedTypes().get(0);
    internal_static_org_example_Serialization_protobuf_Msg_Magic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_Serialization_protobuf_Msg_Magic_descriptor,
        new java.lang.String[] { "Desc", "MagicEnum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
